services:
  mysql:
    image: mysql:8.0
    container_name: Housing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: housing
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - Housing-network

  redis:
    image: redis:latest
    container_name: Housing-redis
    ports:
      - "6384:6379"
    volumes:
      - redis_data:/data
    networks:
      - Housing-network

  # --------------------
  # MongoDB 추가
  # --------------------
  mongo:
    image: mongo:latest
    container_name: Housing-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: housing
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - Housing-network

  postgres:
      image: postgres:latest
      container_name: Housing-postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: housing
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - Housing-network

  spring-app:
    image: housing-image:latest
    container_name: Housing-app
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Housing-mysql:3306/housing
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_MONGODB_URI: mongodb://root:1234@Housing-mongo:27017/housing?authSource=admin
    depends_on:
      - mysql
      - redis
      - mongo
      - postgres
    networks:
      - Housing-network

  nginx:
    image: nginx:latest
    container_name: Housing-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/html
    depends_on:
      - spring-app
    networks:
      - Housing-network

networks:
  Housing-network:
    name: Housing-network

volumes:
  mysql_data:
  redis_data:
  mongo_data:  # MongoDB 볼륨 추가
  postgres_data:  # Postgres 전용 볼륨 추가
