spring:
  application:
    name: BuDongSan

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27018/housing?authSource=admin # MongoDB 연결 추가

    redis:
      host: localhost
      port: 6384

server:
  port: 8080
