spring:
  datasource:
    url: jdbc:postgresql://Housing-postgres:5432/housing
    username: postgres
    password: 1234

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:1234@Housing-mongo:27017/housing?authSource=admin

    redis:
      host: Housing-redis
      port: 6379

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

kakao:
  js-api-key: ${KAKAO_JS_API_KEY}
  rest-api-key: ${KAKAO_REST_API_KEY}

file:
  upload-dir: /home/ubuntu/Room91/images/

news:
  video-dir: /home/ubuntu/Room91/news_videos

server:
  port: 8088