spring:
  application:
    name: BuDongSan

#  profiles:
#    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/housing
    username: postgres
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27018/housing?authSource=admin # MongoDB 연결 추가

    redis:
      host: localhost
      port: 6384

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080

kakao:
  js-api-key: ${KAKAO_JS_API_KEY}
  rest-api-key: ${KAKAO_REST_API_KEY}

file:
  upload-dir: /Users/kangminwoo/projects/Room91/BuDongSan/images/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html