spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: ${SPRING_PORT}

kakao:
  js-api-key: ${KAKAO_JS_API_KEY}
  rest-api-key: ${KAKAO_REST_API_KEY}

google:
  api:
    key: ${GOOGLE_API_KEY}

file:
  upload-dir: ${FILE_UPLOAD_DIR}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

news:
  video-dir: ${NEWS_VIDEO_DIR}

custom:
  base-url: ${CUSTOM_BASE_URL}

logging:
  level:
    root: INFO