spring:
  application:
    name: BuDongSan

  datasource:
    url: jdbc:postgresql://localhost:5432/housing
    username: postgres
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27018/housing?authSource=admin # MongoDB 연결 추가

    redis:
      host: localhost
      port: 6384

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080

kakao:
  rest-api-key: d21c83b1e788c64c8f6d15ac5f7223fc

file:
  upload-dir: /Users/kangminwoo/projects/Room91/BuDongSan/images/