services:
  redis:
    image: redis:latest
    container_name: Housing-redis
    ports:
      - "6384:6379"
    volumes:
      - redis_data:/data
    networks:
      - Housing-network

  mongo:
    image: mongo:latest
    container_name: Housing-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: housing
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - Housing-network

  postgres:
    image: postgres:latest
    container_name: Housing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: housing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Housing-network

  spring-app:
    image: housing-image:latest
    container_name: Housing-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://Housing-postgres:5432/housing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_MONGODB_URI: mongodb://root:1234@Housing-mongo:27017/housing?authSource=admin
      KAKAO_API_KEY: ${KAKAO_API_KEY}
    env_file:
      - .env
    ports:
      - "8088:8080"
    volumes:
      - ./images:/Room91/images/
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - Housing-network

  nginx:
    image: nginx:latest
    container_name: Housing-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www/html
    depends_on:
      - spring-app
    networks:
      - Housing-network

networks:
  Housing-network:
    name: Housing-network

volumes:
  postgres_data:
  redis_data:
  mongo_data:
