name: CI (PR validation)

on:
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BuDongSan
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle build (skip tests temporarily)
        run: ./gradlew clean build -x test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      # PR 환경은 secrets 제한 가능 → 더미 값으로 빌드만 검증
      - name: Generate .env.production (dummy)
        run: |
          echo "VITE_API_BASE_URL=http://localhost:8080" > .env.production
          echo "VITE_KAKAO_JS_API_KEY=dummy" >> .env.production

      - name: Lint & Test (optional)
        continue-on-error: true
        run: |
          npm run lint --if-present
          npm test --if-present -- --ci --watchAll=false

      - name: Build
        run: npm run build
