name: Deploy Spring Boot + React to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot backend
        working-directory: ./BuDongSan
        run: ./gradlew build -x test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # ✅ .env.production 생성 (빌드용 환경변수)
      - name: Generate .env.production
        working-directory: ./frontend
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_KAKAO_JS_API_KEY=${{ secrets.KAKAO_JS_API_KEY }}" >> .env.production

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Copy frontend dist to static/
        run: |
          rm -rf static
          mkdir -p static
          cp -r frontend/dist/* static/

      - name: Check static content
        run: ls -al static

      # ✅ Spring Boot용 .env 파일 생성
      - name: Create backend .env file
        run: |
          echo "KAKAO_JS_API_KEY=${{ secrets.KAKAO_JS_API_KEY }}" > .env
          echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env

      # ✅ .env → EC2 전송 (Spring용)
      - name: Send backend .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ".env"
          target: /home/ubuntu/Room91

      # ✅ .env.production → EC2의 frontend/에 전송
      - name: Send frontend .env.production to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend/.env.production"
          target: /home/ubuntu/Room91/frontend

      # JAR 전송
      - name: Copy backend jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "BuDongSan/build/libs/BuDongSan-0.0.1-SNAPSHOT.jar"
          target: /home/ubuntu/Room91

      # dist(static) 전송
      - name: Copy frontend dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "static"
          target: /home/ubuntu/Room91

      # 서비스 재시작
      - name: Restart services on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/Room91
            docker-compose down
            docker-compose up -d